import type { Product } from "@/lib/google";

// Dummy product data for testing
export const dummyProducts: Product[] = [
  // Men's Products (9 images: men + man)
  {
    id: "men-1",
    name: "Men Item 1",
    description: "Men category product item 1 using men-1 reference image.",
    price: 79,
    category: "men",
    imageUrl: "/images/men-1.jpg",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Navy", "Gray"],
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-2",
    name: "Men Item 2",
    description: "Men category product item 2 using men-2 reference image.",
    price: 64,
    category: "men",
    imageUrl: "/images/men-2.jpg",
    sizes: ["S", "M", "L"],
    colors: ["White", "Navy", "Olive"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-3",
    name: "Men Item 3",
    description: "Men category product item 3 using men-6 reference image.",
    price: 93,
    category: "men",
    imageUrl: "/images/men-6.jpg",
    sizes: ["M", "L", "XL"],
    colors: ["Charcoal", "Stone", "Black"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-4",
    name: "Men Item 4",
    description: "Men category product item 4 using man-6 reference image.",
    price: 58,
    category: "men",
    imageUrl: "/images/man-6.jpg",
    sizes: ["M", "L", "XL"],
    colors: ["Khaki", "Navy", "Black"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-5",
    name: "Men Item 5",
    description: "Men category product item 5 using man-8 reference image.",
    price: 121,
    category: "men",
    imageUrl: "/images/man-8.jpg",
    sizes: ["M", "L", "XL"],
    colors: ["Brown", "Black", "Tan"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-6",
    name: "Men Item 6",
    description: "Men category product item 6 using man-9 reference image.",
    price: 86,
    category: "men",
    imageUrl: "/images/man-9.jpg",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Navy", "Burgundy"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-7",
    name: "Men Item 7",
    description: "Men category product item 7 using man-10 reference image.",
    price: 137,
    category: "men",
    imageUrl: "/images/man-10.jpg",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Charcoal", "Navy"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-8",
    name: "Men Item 8",
    description: "Men category product item 8 using man-11 reference image.",
    price: 74,
    category: "men",
    imageUrl: "/images/man-11.jpg",
    sizes: ["M", "L", "XL"],
    colors: ["Gray", "Black", "Olive"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "men-9",
    name: "Men Item 9",
    description: "Men category product item 9 using man-12 reference image.",
    price: 102,
    category: "men",
    imageUrl: "/images/man-12.jpg",
    sizes: ["S", "M", "L"],
    colors: ["Indigo", "Black", "Blue"],
    featured: false,
    createdAt: new Date().toISOString(),
  },

  // Women's Products (8 images: woman)
  {
    id: "women-1",
    name: "Women Item 1",
    description: "Women category product item 1 using woman-1 reference image.",
    price: 95,
    category: "women",
    imageUrl: "/images/woman-1.jpg",
    sizes: ["XS", "S", "M"],
    colors: ["Rose", "Cream", "Black"],
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-2",
    name: "Women Item 2",
    description: "Women category product item 2 using woman-2 reference image.",
    price: 83,
    category: "women",
    imageUrl: "/images/woman-2.jpg",
    sizes: ["XS", "S", "M"],
    colors: ["Ivory", "Beige", "Wine"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-3",
    name: "Women Item 3",
    description: "Women category product item 3 using woman-3 reference image.",
    price: 109,
    category: "women",
    imageUrl: "/images/woman-3.jpg",
    sizes: ["S", "M", "L"],
    colors: ["White", "Sage", "Sand"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-4",
    name: "Women Item 4",
    description: "Women category product item 4 using woman-4 reference image.",
    price: 117,
    category: "women",
    imageUrl: "/images/woman-4.jpg",
    sizes: ["XS", "S", "M"],
    colors: ["Camel", "Rose", "Charcoal"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-5",
    name: "Women Item 5",
    description: "Women category product item 5 using woman-5 reference image.",
    price: 91,
    category: "women",
    imageUrl: "/images/woman-5.jpg",
    sizes: ["S", "M", "L"],
    colors: ["Burgundy", "Navy", "Black"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-6",
    name: "Women Item 6",
    description: "Women category product item 6 using woman-7 reference image.",
    price: 129,
    category: "women",
    imageUrl: "/images/woman-7.jpg",
    sizes: ["One Size", "S", "M"],
    colors: ["Black", "Tan", "Red"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-7",
    name: "Women Item 7",
    description: "Women category product item 7 using woman-8 reference image.",
    price: 104,
    category: "women",
    imageUrl: "/images/woman-8.jpg",
    sizes: ["S", "M", "L"],
    colors: ["Emerald", "Plum", "Black"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "women-8",
    name: "Women Item 8",
    description: "Women category product item 8 using woman-9 reference image.",
    price: 138,
    category: "women",
    imageUrl: "/images/woman-9.jpg",
    sizes: ["XS", "S", "M"],
    colors: ["Black", "Ivory", "Caramel"],
    featured: false,
    createdAt: new Date().toISOString(),
  },

  // Children's Products (5 images: kids)
  {
    id: "children-1",
    name: "Children Item 1",
    description: "Children category product item 1 using kids-1 reference image.",
    price: 27,
    category: "children",
    imageUrl: "/images/kids-1.jpg",
    sizes: ["4T", "6", "8"],
    colors: ["Blue", "Red", "Yellow"],
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "children-2",
    name: "Children Item 2",
    description: "Children category product item 2 using kids-2 reference image.",
    price: 31,
    category: "children",
    imageUrl: "/images/kids-2.jpg",
    sizes: ["4T", "6", "8"],
    colors: ["Green", "Blue", "Purple"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "children-3",
    name: "Children Item 3",
    description: "Children category product item 3 using kids-3 reference image.",
    price: 35,
    category: "children",
    imageUrl: "/images/kids-3.jpg",
    sizes: ["4T", "6", "8"],
    colors: ["Indigo", "Blue", "Gray"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "children-4",
    name: "Children Item 4",
    description: "Children category product item 4 using kids-4 reference image.",
    price: 29,
    category: "children",
    imageUrl: "/images/kids-4.jpg",
    sizes: ["3T", "5", "7"],
    colors: ["Pink", "Lavender", "Mint"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "children-5",
    name: "Children Item 5",
    description: "Children category product item 5 using kids-5 reference image.",
    price: 33,
    category: "children",
    imageUrl: "/images/kids-5.jpg",
    sizes: ["5", "7", "10"],
    colors: ["Navy", "Orange", "Yellow"],
    featured: false,
    createdAt: new Date().toISOString(),
  },
];
